/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.SistemaVenda.Apresentacao;

import br.edu.ifnmg.tads.SistemaVendas.DataAccess.ProdutoDAO;
import br.edu.ifnmg.tads.SistemaVendas.DomainModel.Produto;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jessica
 */
public class frmListarProduto extends javax.swing.JInternalFrame {
    ProdutoDAO  dao;
    
    /**
     * Creates new form frmListarProduto
     */
    public frmListarProduto() {
        initComponents();

        dao = new ProdutoDAO();

        List<Produto> produtos = dao.ListarProdutos();

        preencheTabela(produtos);
    }

    private void preencheTabela(List<Produto> lista) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Codigo");
        model.addColumn("Descricao");
        model.addColumn("Preco");

        for (Produto p : lista) {
            Vector valores = new Vector();
            valores.add(0, p.getCodigo());
            valores.add(1, p.getNome());
            valores.add(2, p.getPreco());
            model.addRow(valores);
        }
        tblListarProdutos.setModel(model);
        tblListarProdutos.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtListarProduto = new javax.swing.JTextField();
        btnBuscarproduto = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarProdutos = new javax.swing.JTable();

        txtListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListarProdutoActionPerformed(evt);
            }
        });

        btnBuscarproduto.setText("Buscar");
        btnBuscarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarprodutoActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tblListarProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos"
            }
        ));
        jScrollPane1.setViewportView(tblListarProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarproduto)
                .addGap(18, 18, 18)
                .addComponent(btnNovo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarproduto)
                    .addComponent(btnNovo))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
     frmProdutoCadastro janela = new frmProdutoCadastro();
     this.getParent().add(janela);
     janela.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnBuscarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarprodutoActionPerformed
      Produto produto = new Produto();
       /* try {
            if (txtListarProdutos.getSelectedIndex()== 0){
                produto.setCodigo(Integer.parseInt(txtListarProdutos.getText()));
            }

         
        } catch (Exception ex) {
            Logger.getLogger(frmListarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

        produto = ProdutoDAO.Buscar(produto);

        adicionacursotable(produto);
    
    } */
    }//GEN-LAST:event_btnBuscarprodutoActionPerformed

    private void txtListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListarProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarproduto;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarProdutos;
    private javax.swing.JTextField txtListarProduto;
    // End of variables declaration//GEN-END:variables
}
